app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('contacts/', views.contacts, name='contacts'),
    path('post/<str:slug>', views.post_detail, name='post'),
    path('post_create', views.post_create, name='post_create'),
    path('like/', views.like, name='like'),
    path('delete_post/<str:slug>', views.delete_post, name='delete_post')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('app.urls', 'app'), namespace='app')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

urlpatterns += static(
    settings.STATIC_URL,
    document_root=settings.STATIC_ROOT)

urlpatterns += static(
    settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('sign-in', views.sign_in, name='sign-in'),
    path('sign-up', views.sign_up, name='sign-up'),
    path('sign-out', views.sign_out, name='sign-out')
]

app/models.py
from django.db import models
from django.contrib.auth.models import User


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    slug = models.SlugField(unique=True)
    date_created = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comments_allowed = models.BooleanField(default=True)
    likes = models.ManyToManyField(User, related_name='likes')
    dislikes = models.ManyToManyField(User, related_name='dislikes')

    def __str__(self):
        return self.title

    def slice(self):
        return ' '.join(self.content.split(' ')[:3]) + '...'


class Photo(models.Model):
    image = models.ImageField(default='image.jpg', blank=True)
    post = models.ForeignKey('app.Post', null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.image.url


class Comment(models.Model):
    body = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name='comment_likes')
    dislikes = models.ManyToManyField(User, related_name='comment_dislikes')
    parent = models.ForeignKey(
        'self', null=True, blank=True, on_delete=models.CASCADE, related_name='reply'
    )
    first_comment = models.ForeignKey(
        'self', null=True, blank=True, on_delete=models.CASCADE, related_name='main_comment'
    )

    def __str__(self):
        return self.body

app/templates/about.html
{% extends 'layout.html' %}

{% block content %}
<div class="container has-text-centered">
    <div class="title has-text-white">
        Страница о компании
    </div>
</div>
{% endblock %}

app/templates/contacts.html
{% extends 'layout.html' %}

{% block content %}
<div class="container has-text-centered">
    <div class="title has-text-white">
        Страница c контактами
    </div>
</div>
{% endblock %}

app/templates/delete_post.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <div class="columns is-centered">
        <div class="column is-5">
            <form method="post" class="box has-background-light">
                {% csrf_token %}
                <p class="title has-text-centered is-4 mb-5 has-text-black">
                    Подтвердите удаление поста "{{ post }}"
                </p>
                <div class="has-text-centered">
                    <button class="button is-danger">Подтвердить</button>
                    <a class="button is-warning" href="{% url 'app:post' post.slug %}">
                        Назад к посту
                    </a>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'layout.html' %}


{% block content %}
<div class="container">
    <div class="columns is-centered is-multiline">
        {% for post in posts %}
        <div class="column is-4">
            <div class="box" style="min-height: 200px;">
                <div class="title has-text-centered">
                    {{ post.title }}
                </div>
                <div class="content has-text-grey-light">
                    {{ post.slice }}
                </div>
                <a href="{% url 'app:post' post.slug %}" class="button is-fullwidth is-info is-outlined is-size-5">
                    Читать далее
                    &#8594
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% include 'pagination.html' with objects=posts %}
</div>
{% endblock %}

app/templates/layout.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js"></script>
    <script src="{% static 'script.js' %}" defer></script>
</head>

<body>
    <div class="modal">
        <div class="modal-background"></div>
        <div class="modal-content">
            <div class="box modal-box" style="min-height: 30vh;">
                <div class="title is-3 has-text-centered">
                    Подтвердите выход.
                    <br>
                    Активная сессия будет закрыта.
                </div>
                <div class="buttons is-centered">
                    <a href="{% url 'users:sign-out' %}" class="button is-success">ОК</a>
                    <a href="{{ request.path }}" class="button is-warning">Назад</a>
                </div>
            </div>
        </div>
        <button onclick="showOrHideModal()" class="modal-close is-large" aria-label="close"></button>
    </div>
    <section class="hero has-background-info is-fullheight">
        <div class="hero-head">
            <header class="navbar">
                <div class="container">
                    <div class="navbar-brand">
                        <a class="navbar-item" href="{% url 'app:index' %}">
                            <img src="https://bulma.io/assets/images/bulma-type-white.png" alt="Logo" />
                        </a>
                        <span class="navbar-burger" data-target="navbarMenuHeroC">
                            <span></span>
                            <span></span>
                            <span></span>
                        </span>
                    </div>
                    <div id="navbarMenuHeroC" class="navbar-menu">
                        <div class="navbar-star t">
                            <div class="navbar-item">
                                <div class="dropdown is-hoverable">
                                    <div class="dropdown-trigger">
                                        <a class="button is-info is-outlined is-inverted">
                                            Пост
                                        </a>
                                    </div>
                                    <div class="dropdown-menu">
                                        <div class="dropdown-content">
                                            <a href="{% url 'app:post_create' %}" class="dropdown-item">
                                                <ion-icon name="create" class="is-size-6"></ion-icon>
                                                <span class="my-3">Создать пост</span>
                                            </a>
                                        </div>
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="navbar-end">


                            <span class="navbar-item">
                                <div class="dropdown is-hoverable">
                                    <div class="dropdown-trigger">
                                        <a class="button is-info is-outlined is-inverted">
                                            {% if user.is_authenticated %}
                                            {{user}}
                                            {% else %}
                                            Неизвестный юзер
                                            {% endif %}
                                        </a>
                                    </div>
                                    <div class="dropdown-menu">
                                        <div class="dropdown-content">
                                            {% if not user.is_authenticated %}
                                            <a href="{% url 'users:sign-in' %}" class="dropdown-item">
                                                Войти
                                            </a>
                                            <a href="{% url 'users:sign-up' %}" class="dropdown-item">
                                                Зарегистрироваться
                                            </a>
                                            {% else %}
                                            <a onclick="showOrHideModal()" class="dropdown-item has-text-danger">
                                                Выйти
                                            </a>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </span>
                            <a href="{% url 'app:index' %}"
                                class="navbar-item {% if request.path == '/' %} is-active {% endif %}"> Home </a>
                            <a href="{% url 'app:about' %}"
                                class="navbar-item {% if request.path == '/about/' %} is-active {% endif %}"> About </a>
                            <a href="{% url 'app:contacts' %}"
                                class="navbar-item {% if request.path == '/contacts/' %} is-active {% endif %}">
                                Contacts
                            </a>
                        </div>
                    </div>
                </div>
            </header>
        </div>


        <div class="hero-body">
            {% block content %}
            {% endblock %}
        </div>
    </section>
</body>

</html>

app/templates/likes.html
<form class="has-text-right" action="{% url 'app:like' %}">
    <input type="hidden" name="model" value="{{ object_name }}">
    <input type="hidden" name="value"
        value="{% if object_name == 'comment' %}{{object.pk}}{% else %}{{object.slug}}{% endif %}">

    <button class="button {% if user in object.likes.all %} is-success {% endif %}" value="like" name="action">
        <ion-icon name="thumbs-up"></ion-icon>
        <span class="ml-3">{{object.likes.count}}</span>
    </button>
    <button class="button {% if user in object.dislikes.all %} is-danger {% endif %}" value="dislike" name="action">
        <ion-icon name="thumbs-down"></ion-icon>
        <span class="ml-3">{{object.dislikes.count}}</span>
    </button>
</form>

app/templates/pagination.html
{% if objects.has_other_pages %}
<nav class="pagination is-centered">
    <div class="buttons is-left">
        {% if objects.has_previous %}
        <a class="pagination-previous" href="?page={{objects.previous_page_number}}">Назад</a>
        <a class="pagination-link" href="?page=1">В начало</a>
        {% else %}
        <button class="pagination-previous" disabled>Назад</button>
        {% endif %}       
    </div>

    <div class="buttons is-centered">
        <ul class="pagination-list">
            {% for page in objects.paginator.page_range %}
            <li>
                <a class="pagination-link{% if page == objects.number %} is-current {% endif %}" href="?page={{page}}">{{ page }}</a>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="buttons is-right">
        {% if objects.has_next %}
        <a class="pagination-next" href="?page={{objects.next_page_number}}">Далее</a>
        <a class="pagination-next" href="?page={{ objects.paginator.num_pages }}">В конец</a>
        {% else %}
        <button class="pagination-next" disabled>Далее</button>
        {% endif %}       
    </div>
</nav>
{% endif %}

app/templates/post.html
{% extends 'layout.html' %}

{% block content %}
<div class="column">
    <div class="box" style="min-width: 100%; min-height: 80vh;">
        <div class="buttons is-right">
            <a href="{% url 'app:delete_post' post.slug %}" class="button">
                <ion-icon name="trash"></ion-icon>
            </a>
        </div>
        <div class="title has-text-centered">
            {{ post.title }}
        </div>

        <div class="columns is-centered is-multiline" style="width: 100%;">
            {% with photos=post.photo_set.all %}
            {% for image in photos %}
            <div class="column {% if photos|length > 1 %} is-5 {% else %} is-12 {% endif %}">
                <img style="width: 100%;" src="{{ image.image.url }}" alt="" class="image post-image">
            </div>
            {% endfor %}
            {% endwith %}
        </div>
        <div class="content has-text-centered">
            {{post.content}}
        </div>
        <hr>
        {% include 'likes.html' with object=post object_name="post" %}
        <div class="author">
            <div class="columns is-centered is-vcentered">
                <div class="column is-3">
                    <hr />
                </div>
                <div class="column is-1 image">
                    <figure class="image is-128x128">
                        <img class="is-rounded" src="https://bulma.io/assets/images/placeholders/128x128.png" alt="" />
                    </figure>
                </div>
                <div class="column is-3">
                    <hr />
                </div>
            </div>
            <div class="has-text-centered">
                <div class="title">{{post.author}}</div>
                <div class="subtitle has-text-grey">Junior Backend Разработчик</div>
                <a class="content has-text-link is-size-5">Постов: 5</a>
            </div>
        </div>
    </div>
    {% if post.comments_allowed %}
    <div class="box">
        {% if user.is_authenticated %}
        <form action="" class="comment-form" method="post">
            {% csrf_token %}
            {% for field in form %}
            {{field}}
            {% endfor %}
            <button>Отправить</button>
        </form>
        <div>
            {% for comment in post.comment_set.all %}
            <div class="columns is-centered">
                <div class="column is-1">
                    <div class="media">
                        <div class="media-left">
                            <figure class="image">
                                <img class="is-rounded" src="https://bulma.io/assets/images/placeholders/48x48.png"
                                    alt="">
                            </figure>
                        </div>
                    </div>
                </div>
                <div class="column is-4">
                    <div class="box">
                        <!-- {% if comment.parent %}
                        <div class="has-text-right has-text-info">
                            <span class="mr-1">
                                <ion-icon name="arrow-undo"></ion-icon>
                            </span>
                            <span>В ответ на {{ comment.parent.user }}</span>
                        </div>
                        {% endif %} -->
                        <div class="title is-3">
                            {{comment.user}}
                        </div>
                        <div class="subtitle has-text-grey is-6">
                            {{comment.date}}
                        </div>
                        <div class="content">
                            {{comment.body}}
                        </div>

                        {% include 'likes.html' with object=comment object_name="comment" %}
                        <div class="buttons is-right">
                            <button class="button is-small" name="reply"
                                onclick="toggleReplyForm('comment-{{comment.pk}}')">
                                <ion-icon name="arrow-undo"></ion-icon>
                            </button>
                        </div>
                        <form class="comment-form is-hidden" method="post" id="comment-{{comment.pk}}">
                            {% csrf_token %}

                            <input type="hidden" name="parent_id" value="{{comment.pk}}">

                            {% for field in form %}
                            {{field}}
                            {% endfor %}
                            <button>
                                Отправить
                            </button>
                        </form>
                        
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <div class="title is-4 has-text-centered">
            Авторизуйтесь, чтобы увидеть комментарии
        </div>
        {% endif %}
    </div>
    {% else %}
    <div class="title has-text-white has-text-centered">
        Автор запретил комментирование
    </div>
    {% endif %}
    {% include "pagination.html" with objects=comments %}
</div>
{% endblock %}

app/templates/post_create.html
{% extends 'layout.html' %}

{% block content %}
<div class="modal is-active">
    <div class="modal-background"></div>
    <div class="modal-content box">
        <div class="title has-text-centered">Создание поста</div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% for field in post_form %}
            <div class="field">
                {% if field.name == 'comments_allowed' %}
                <label for="{{field.id_for_label}}">
                    {{field}}
                    {{field.label}}
                </label>
                {% else %}
                <div class="control">
                    {{field}}
                </div>
                {% endif %}
            </div>
            {% endfor %}
            <div class="file field">
                <label class="file-label">
                    <input class="file-input" type="file" name="images" multiple>
                    <span class="file-cta">
                        <span class="file-icon">
                            <ion-icon name="cloud-upload-outline">
                            </ion-icon>
                        </span>
                        <span class="file-label">
                            Выберите файлы…
                        </span>
                    </span>
                </label>
            </div>
            <button class="button is-fullwidth is-success">
                Отправить
            </button>
        </form>
    </div>
    <a class="modal-close is-large" onclick="window.history.back()"></a>
</div>
{% endblock %}